### ISSUE TITLE
Method invokable_worker_methods missing

### ISSUE THREAD

**Issue by kakra** [gnufied/backgroundrb#3]
Please have a look at my comment on the code:
http://github.com/gnufied/backgroundrb/commit/22d365a4df4b49d29774efdb5a9335e0300a3ac9#server/lib/master_worker.rb-P27

The method which should be called there doesn't seem to be defined anywhere...

**Comment by gnufied** [comment]
You need to update your packet version to 0.1.15 for that to work. Basically, that change allows for instant exception thrown in user code, if you are trying to invoke a method on worker which isn't defined in worker.Needless to say, it also defeats method_missing kinda hack too.

**Comment by gnufied** [comment]
Closing it.

**Comment by kakra** [comment]
Would there be a way to check the minimum requirements during application startup?

**Comment by krisleech** [comment]
Is this the same error as:
#<NoMethodError: undefined method `invokable_worker_methods' for nil:NilClass>

I have Packet 0.1.15 installed and have restarted the workers.
